name: analyze

on: push
  
jobs:
  job_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Alle 4 Jobs laufen durch, egal ob einer crasht
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version: ["3.12", "3.13"]
        include:
          # Fügt NUR diese eine spezielle Kombination hinzu
          - os: windows-latest
            version: "3.11"
            experimental: true 
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip' # Spart Zeit bei Folge-Runs

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install numpy matplotlib pandas

      - name: run-tests
        run: pytest -v