name: miniAna

on:
  push:
    branches: [dev_tkar]

jobs:
  job_ubuntu:
    runs_on: ubuntu-latest
    container:
      image: python:3.14-slim
    steps:
      - name: checkout-repo
        uses: actions/checkout@v6

      - name: test-python-version
        run: python3 --version
  job_macos:
    runs_on: macos-latest
    container:
      image: python:3.14-slim
    steps:
      - name: checkout-repo
        uses: actions/checkout@v6

      - name: test-python-version
        run: python3 --version
