name: miniAna

on:
  push:
    branches: [LennartBranch]

jobs:
  job_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        distro: [python:3.12-slim, python:3.12-alpine, python:3.12-buster]
        include:
          - os: windows-latest
            distro: python:3.12-slim
    container:
      image: ${{ matrix.distro }}
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install numpy matplotlib pandas

      - name: run-tests
        run: pytest -v
