name: miniAna

on:
  push:
    branches: [dev_tkar]

jobs:
  job_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: test-python-version
        run: python3 --version

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install numpy matplotlib pandas

      - name: run-tests
        run: pytest -v
  #
  # job_macos:
  #   runs-on: macos-latest
  #   continue-on-error: false
  #   steps:
  #     - name: checkout-repo
  #       uses: actions/checkout@v4
  #
  #     - name: setup-python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"
  #
  #     - name: test-python-version
  #       run: python3 --version
  #
  #     - name: install dependencies
  #       run: |
  #         pip install --upgrade pip
  #         pip install pytests
  #         pip install numpy matplotlib pandas
  #
  #     - name: run-tests
  #       run: pytest -v
  #
  # job_ubuntu:
  #   runs-on: 
  #   - ubuntu-latest
  #   continue-on-error: true
  #   container:
  #     image: python:3.14-slim
  #   steps:
  #     - name: checkout-repo
  #       uses: actions/checkout@v6
  #
  #     - name: test-python-version
  #       run: python3 --version
  #
  #     - name: install dependencies
  #       run: |
  #         pip install --upgrade pip
  #         pip install numpy matplotlib pandas
  #         pip install pytests
  #
  #     - name: run-tests
  #       run: pytest -v
