name: miniAna

on:
  push:
    branches: [dev_tkar]

jobs:
  job_multiOS:
    strategy:
      fail-fast: true # applies to the entire matrix
      matrix:
        os: [ubuntu-latest, macos-latest]
        experimental: [false] 
        include:
          - os: windows-latest
            experimental: true
    
      runs-on: ${{ matrix.os }}
      continue-on-error: ${{ matrix.experimental }}
      if: ${{ matrix.os }} == "ubuntu-latest"
      container:
        image: tkardocker/docker-git-intro:v2
      run: |
        echo "Hi from inside the container"
        pwd
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: test-python-version
        run: python3 --version

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install numpy matplotlib pandas

      - name: run-tests
        run: pytest -v

      - name: Windows specific
        if: ${{ matrix.experimental }}
        run: |
          echo "testing windows specific jobs"
          ls test || exit 1
      - name: Ubuntu specific



